---
output: 
  html_document:
    toc: true
    toc_float: true
---

### **Discussion**

In this data investigation, we explored COVID vaccination and booster trends in NYC as of March 9th, 2022 (approximately 90 days after the booster was approved for all individuals aged 18 and above). We specifically explored patterns between the proportion of individuals vaccinated or boosted in NYC neighborhoods and the following demographic variables: education, median income, and poverty status. 

<br>

#### **Key Findings vs. Expectations**
We anticipated observing a higher vaccination rate in more affluent boroughs such as Manhattan. We noted that Staten Island and the Bronx had the lowest vaccination completion rates among all boroughs, with more than 2 doses of the initial series seen in Manhattan. 

Manhattan, Queens, and Brooklyn had similar booster dose administration in the adult population, while the Bronx and Staten Island had lower rates of administration comparatively. 

We were surprised to find that educational attainment was not a significant influencer in obtaining booster vaccination, or completion of the full vaccination series when comparing different boroughs in NYC. 

When comparing median household income in different boroughs to proportion of fully vaccinated adult population, we did not observe variability among different boroughs. However, it was illuminating to see that there is a possible correlation between median household income and receiving booster COVID vaccinations in all boroughs. It appeared that there was a positive linear relationship between  median household income and proportion of boosted adults, with neighborhoods that had a greater median income having a greater proportion of boosted adults. When broken down by borough, however, this pattern was not observed in Staten Island or Queens. 

To look at economic background in a different lens, we compared rates of adult vaccinations compared to rate of poverty (as determined by rates below federal poverty line). Based on the previous income assessment, we hypothesized no variation between the rate of full vaccination and poverty status as all individuals were required to receive vaccinations. We were surprised to notice that there were income differences in neighborhoods with high versus low vaccination rates, with neighborhoods with lower poverty rates tended to have a higher proportion of people fully vaccinated. In particular these differences were driven by the fact that in high income neighborhoods, individuals appeared to seek multiple rounds of full vaccination, beyond the mandated single dose. 

As boosters are optional preventative care, we hypothesized that neighborhoods with higher poverty status would have lower booster rates. This expectation held true based on the data. We noticed that there was an inverse relationship between rate of poverty and completion of boosted vaccination shots across NYC. One exception was Staten Island where despite low poverty rates relative to other boroughs, booster rates were low as well. 

<br>

#### **What insights into the data did we make?**
Given our observation of the data, we were curious if education levels, access to vaccination, or socioeconomic status was influential in the lower booster rates seen in the Bronx and Staten Island.

Interestingly, regardless of the education status, booster immunization was consistently higher in Manhattan and Queens, and lower in Staten Island and the Bronx. This hints to the likelihood that educational attainment may not be a key influencer of receiving COVID booster vaccines. 

In all boroughs except for Staten Island, we noted that economic background (as portrayed by median household income and poverty rate) was not associated with completion of the original vaccine series, but related to receiving boosters among adults.

Future analyses can examine factors that may drive lower booster rates among communities. Such factors may consist of both infrastructure barriers (access to subways, pharmacies, clinics) as well as psychosocial factors (attitudes towards vaccines, health education, personal COVID history).

<br>

#### **Recommendations for further Research and Analysis of this topic.**

1. Explore how factors in race and health care access relate to vaccine and booster uptake. 

2. Identify how city infrastructure (e.g. subway access, health clinics) relates to vaccine and booster uptake.

3. Identify communities in which to focus booster efforts and novel ways to advocate for booster immunization.

4. Study appropriate differential resource allocation to boroughs with lower vaccination and booster rates (the Bronx and Staten Island). 

5. Explore other psychosocial variables (e.g. vaccine attitudes, political affiliation, health literacy) to understand differences across boroughs and neighborhoods. 

6. Investigate how vaccination trends differ among the pediatric population compared to adults.

<br> 

#### **References:**
1. [Carrión, D., Colicino, E., Pedretti, N.F. et al. Neighborhood-level disparities and subway utilization during the COVID-19 pandemic in New York City. Nat Commun 12, 3692 (2021).](https://doi.org/10.1038/s41467-021-24088-7)

2. [Williams N, Tutrow H, Pina P, Belli HM, Ogedegbe G, Schoenthaler A. Assessment of Racial and Ethnic Disparities in Access to COVID-19 Vaccination Sites in Brooklyn, New York. JAMA Netw Open. 2021 Jun 1;4(6):e2113937. doi: 10.1001/jamanetworkopen.2021.13937. PMID: 34143195; PMCID: PMC8214153.](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC8214153/)

3. [Magesh S, John D, Li WT, et al. Disparities in COVID-19 Outcomes by Race, Ethnicity, and Socioeconomic Status: A Systematic Review and Meta-analysis. JAMA Netw Open. 2021;4(11):e2134147. doi:10.1001/jamanetworkopen.2021.34147](https://jamanetwork.com/journals/jamanetworkopen/fullarticle/2785980)