---
title: "Exploratory Analysis"
output: 
  html_document:
    toc: true
    toc_float: true
---
```{r setup, include = FALSE}
library (tidyverse)
library (readxl)
library(plotly)
library(esquisse)


knitr::opts_chunk$set(
	echo = TRUE,
	warning = FALSE,
	fig.width = 8, 
  fig.height = 6,
  out.width = "90%"
)
theme_set(theme_minimal() + theme(legend.position = "bottom"))
options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)
scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d

vaccine_coverage_df = read_csv(file = "./data/coverage_by_modzcta_adults.csv") %>% 
  janitor::clean_names() %>% 
  mutate(count_partially_prop = round(count_partially_cumulative/pop_denominator,2), count_Fully_prop = round(count_fully_cumulative/pop_denominator,2), count_1Plus_prop = round(count_1plus_cumulative/pop_denominator,2), count_Additional_prop = round(count_additional_cumulative/pop_denominator,2))
```

# **1. The vaccination coverage in NYC**


# **2. The booster coverage in NYC**


# **3. The Education Attainment vs vaccination and booster coverage **

# **4.. The Poverty Status vs vaccination and booster coverage**

```{r, include=FALSE}

#### Load and clean poverty data; select data relevant for 18+

data = read_csv(file ="./data/poverty_status.csv", skip = 1) %>%
  janitor::clean_names()

dataset_clean = data %>% 
  mutate(modzcta = substr(geographic_area_name,6,11),
         total_pop_pov_det_18_and_over = estimate_total_population_for_whom_poverty_status_is_determined - estimate_total_population_for_whom_poverty_status_is_determined_age_under_18_years) %>% 
  mutate(below_pov_level_pop_pov_det_18_and_over = estimate_below_poverty_level_population_for_whom_poverty_status_is_determined - estimate_below_poverty_level_population_for_whom_poverty_status_is_determined_age_under_18_years) %>%
  select(modzcta, total_pop_pov_det_18_and_over, below_pov_level_pop_pov_det_18_and_over)

```


```{r, include=FALSE}
### Divide "status determined" by "below poverty level" to find proportion
dataset_clean = dataset_clean %>% 
  mutate(prop_below_pov_level_18_and_over = below_pov_level_pop_pov_det_18_and_over / total_pop_pov_det_18_and_over)
```


```{r, include =FALSE}
### Load zipcode data

zipcode_data = read_csv(file = "./data/Modified_Zip_Code_Tabulation_Areas__MODZCTA_.csv")
```


```{r, include = FALSE}
### Load and clean vaccine data

vaccine_data = read_csv(file ="./data/coverage_by_modzcta_adults.csv") %>%
  janitor::clean_names() %>%
  mutate(modzcta = as.character(modzcta))

vaccine_data$modzcta <- gsub('\\s+', '', vaccine_data$modzcta)
dataset_clean$modzcta <- gsub('\\s+', '', dataset_clean$modzcta)
```


```{r, include = FALSE}
### Join data

joined_dataset_poverty = merge(vaccine_data,dataset_clean, by = "modzcta", all.x = TRUE)
```


```{r, include = FALSE}
### Create proportions for vaccine data

joined_dataset_poverty = joined_dataset_poverty %>% 
  mutate(
  prop_partially = count_partially_cumulative / pop_denominator,
    prop_fully = count_fully_cumulative / pop_denominator,
    prop_booster = count_additional_cumulative / pop_denominator
  )
```

Fully vaccinated:

```{r, echo=FALSE}
joined_dataset_poverty %>% 
  ggplot(aes(x = prop_below_pov_level_18_and_over, y = prop_fully, color = borough)) +
  geom_point()
```

Partially vaccinated:

```{r,echo=FALSE}
joined_dataset_poverty %>% 
  ggplot(aes(x = prop_below_pov_level_18_and_over, y = prop_partially, color = borough)) +
  geom_point()
```

Booster:

```{r,echo=FALSE}
joined_dataset_poverty %>% 
  ggplot(aes(x = prop_below_pov_level_18_and_over, y = prop_booster, color = borough)) +
  geom_point()
```

Zipcode and variable: 

```{r,echo=FALSE}
joined_dataset_poverty %>% 
  ggplot(aes(x = prop_below_pov_level_18_and_over, y = borough, color = borough)) +
  geom_point()
```


### **5. The Median Income vs vaccination and booster coverage**

```{r income_data_preprocessing, paged.print=TRUE,include=FALSE}
#Loading income data 
incomedata <- read_csv("data/median_income.csv", skip = 1)

#Loading zipcode data 
zipcode_data <- read.csv("data/Modified_Zip_Code_Tabulation_Areas__MODZCTA_.csv")

incomedata_clean <- incomedata %>%  
  janitor::clean_names()  %>%
  select(geography, geographic_area_name, estimate_median_income_dollars_families_families, estimate_median_income_dollars_nonfamily_households_nonfamily_households) %>%
  rename (median_income_nonfamily = estimate_median_income_dollars_nonfamily_households_nonfamily_households, median_income_family = estimate_median_income_dollars_families_families) %>% 
  separate(geographic_area_name, c('delete', 'modzcta')) %>% 
  select(modzcta, median_income_family, median_income_nonfamily)

vaccine_data <- read.csv("data/coverage_by_modzcta_adults.csv") %>%
  janitor::clean_names() %>%
  mutate(modzcta = as.character(modzcta))

vaccine_data$modzcta <- gsub('\\s+', '', vaccine_data$modzcta)

```

```{r merege-dataset,include=FALSE}
joined_dataset_income = merge(vaccine_data,incomedata_clean, by = "modzcta", all.x = TRUE)
```

```{r,echo=FALSE}
#Cleaning variables in joined data and changing into the correct variable type 

income_zip_clean <- joined_dataset_income %>%
  mutate(modzcta = as.numeric(modzcta), median_fam = as.numeric(median_income_family), median_nonfam = as.numeric(median_income_nonfamily)) %>% 
  mutate(median_fam = if_else(is.na(median_fam), 250000, median_fam)) %>% 
  filter(!is.na(median_nonfam)) %>% 
  select(modzcta, pop_denominator, count_partially_cumulative, count_fully_cumulative, count_1plus_cumulative, count_additional_cumulative, median_fam, median_nonfam, borough) %>% 
  mutate(Count_partially_prop = round(count_partially_cumulative/pop_denominator,2), Count_Fully_prop = round(count_fully_cumulative/pop_denominator,2), Count_1Plus_prop = round(count_1plus_cumulative/pop_denominator,2), Count_Additional_prop = round(count_additional_cumulative/pop_denominator,2), income_average = ((median_fam + median_nonfam)/2))

str(income_zip_clean)

```

```{r,echo=FALSE}
#GGPLOT of Vaccination and family median income and non family median income by borough

income_zip_clean %>%
    ggplot() +
    geom_point(aes(x = median_fam, y=Count_Fully_prop, color=borough), alpha = 0.5)+
  labs(
   title = "Proportion Vaccinated & Median Family Income by Borough", 
    x = "Median Family Income", 
    y = "Proportion Vaccinated (Count_Fully_Prop)")

#GGPLOT of Vaccination and nonfamily median income and non family median income by borough
income_zip_clean %>%
    ggplot() +
    geom_point(aes(x = median_nonfam, y=Count_Fully_prop, color=borough), alpha = 0.5)+
  labs(
   title = "Proportion Vaccinated & Median Nonfamily Income by Borough", 
    x = "Median nonfamily Income", 
    y = "Proportion Vaccinated (Count_Fully_Prop)")

#GGPLOT of Vaccination combined median income and non family median income by borough

income_zip_clean %>%
    ggplot() +
    geom_point(aes(x = income_average, y=Count_Fully_prop, color=borough), alpha = 0.5)+
  labs(
   title = "Proportion Vaccinated & Median Income by Borough", 
    x = "Median Income (family + nonfamily)", 
    y = "Proportion Vaccinated (Count_Fully_Prop)")


```

```{r,echo=FALSE}
#GGPLOT OF BOOSTER STATUS AND MEDIAN INCOME 
income_zip_clean %>%
    ggplot() +
    geom_point(aes(x = median_fam, y=Count_Additional_prop, color=borough), alpha = 0.5)+
  labs(
   title = "Proportion Boosted & Median Family Income by Borough", 
    x = "Median Family Income", 
    y = "Proportion Boosted (Count_Additional_Prop)")


income_zip_clean %>%
    ggplot() +
    geom_point(aes(x = median_nonfam, y=Count_Additional_prop, color=borough), alpha = 0.5)+
  labs(
   title = "Proportion Boosted & Median Nonfamily Income by Borough", 
    x = "Median nonfamily Income", 
    y = "Proportion Boosted (Count_Additional_Prop)")

income_zip_clean %>%
    ggplot() +
    geom_point(aes(x = income_average, y=Count_Additional_prop, color=borough), alpha = 0.5)+
  labs(
   title = "Proportion Boosted & Median  Income by Borough", 
    x = "Median Income (family + nonfamily)", 
    y = "Proportion Boosted (Count_Additional_Prop)")


```

