---
output: 
  html_document:
    toc: true
    toc_float: true
---
# **Project Report for P8105**
#### *By Brittany Shea | Erfan Faridmoayer| Niharika Telrandhe| Pooja Desai | Sabah Usmani*

## **Project Motivation**

Throughout the course of the COVID-19 pandemic, vaccine availability played a significant role in reduction of new cases, while reducing symptom severity among people who were infected. With the rise of new variants, the need for booster vaccinations with new COVID strain coverage was evident. 

There were widespread reports of lack of vaccine availability in many areas, especially among those with lower socioeconomic status and limited geographic resource availability. 

Given these reports, we wanted to explore the following -

1. Factors that make neighborhoods in NYC vulnerable.
2. Trends in vaccination - how people are vaccinated - fully (FDA approved primary series) , partially( 1-dose of FDA approved primary series)  or with booster (1 complete FDA-approved primary series + additional boosters).
3. How many people are actually getting vaccinated?
COVID-19 vaccination and booster distribution by zip codes and boroughs in NYC as of 2022.
4. Disparities in vaccine distribution with respect to geographic location, poverty status, education attainment and median income.
5. Sociodemographic trends in individuals receiving complete vaccinations and boosters.

### *Related Work*

The `ggplot function` in R combined with the [New York City COVID-19 geographic mapping](https://www.nyc.gov/site/doh/covid/covid-19-data.page) found here was the inspiration for us to further evaluate the trends in vaccine and booster distribution across New York City based on the available zip codes.

## **Initial Questions**
Q1. What socio-demographic and geographic factors make a neighborhood vulnerable with respect to COVID-19 vaccination and boosters.
Q2. How many people were vaccinated - partially, fully and with boosters ?
Q3. How education attainment, poverty status, median income was affecting vaccination and booster distribution in NYC.
Q4.Vaccination and booster distribution with respect to zipcodes in NYC.

### *Evolution of Analytic Questions*

### *New Questions Identified During Analysis*

## **Additional Analyses**

## **Discussion**

### *Key Findings*

### *Were the Findings as Expected?*

### *What insights into the data did we make?*

### *Suggestions/Recommendations for further Research and Analysis of this topic.*


